let url = "http://47.99.198.85";
// let url = "http://api.times168.net";

/**
 * @module  api
 * api请求的地址常量
 * */

export const HOME_NOTICE = '/Home/index/notice';
export const HOME_INDEX = '/Home/index/index';//firstpage信息
export const HOME_PRODUCTS = '/Home/index/products';
export const LOGIN = '/Home/login/login';//登录
export const GET_USERINFO = '/Home/user/user_info';
export const GET_LOGIN_CAPTCHA = '/login/sendRandomCaptcha';
export const SMSVERIFY = '/Home/register/smsverify';//发送验证码
export const REGISTER = '/Home/register/index';//注册
export const MY_CUSTOMER = '/Home/user/my_customer';//一级佣金
export const MY_SCUSTOMER = '/Home/user/my_scustomer';//二级佣金
export const FUND_DETAILS = '/Home/fund/details';//收支页面顶部数据
export const FUND_DETAILS_NEXT_PAGE = '/home/fund/details_next_page';//收支页面下面数据（每次10条）
export const UPFILE_UPLOAD_BASE64 = 'home/upfiles/upload';//图片文件上传

// export const GET_LOGIN_CAPTCHA = url+'/login/captcha';
// export const LOGIN = url+'/login';//登录
// export const REGISTER = url+'/register';//注册
// export const SEND_VERIFI_CODE = url+'/send_verifi_code';//获取验证码
// export const BIND_SEND_VERIFI_CODE = url+'/bind_send_verifi_code';//获取验证码
// export const GET_LEADER_BOARD = url+'/leaderboard';//查看排行榜
// export const GET_USER_MEDAL = url+'/user_medal';//个人勋章列表
// export const GET_USER_INFO = url+'/user_info';//个人勋章列表
// export const EDIT_USERNAME = url+'/edit_username';//个人勋章列表
// export const COUPON = url+'/coupon';//活动页优惠券
// export const JOIN_ROOM_ID = url+'/join_room_id';//加入房间
// export const CREATE_ROOM = url+'/create_room';//创建房间
// export const CONFIRM_ROOM_PASS = url+'/confirm_room_pass';//验证房间密码
// export const RADOME_JOIN_ROOM = url+'/join_room';//加入房间
// export const UPLOAD_MY_HEAD = url+'/upload';//上传头像
// export const UPDATE_USERINFO = url+'/update_userinfo';//更新用户信息
// export const ADD_USER_LIST = url+'/add_user_list';//添加好友列表
// export const BATCH_AGREE_APPLY = url+'/batch_agree_apply';//同意添加好友
// export const OTHER_USER_INFO = url+'/other_user_info';//好友信息
// export const BATCH_REFUSE_APPLY = url+'/batch_refuse_apply';//拒绝添加好友
// export const BATCH_ADD_USER = url+'/batch_add_user';//申请添加好友
// export const SELF_FRIEND = url+'/self_friend';//好友列表
// export const BEGIN_GAME = url+'/begin_game';//开始游戏
// export const CHALL_RES = url+'/chall_res';//游戏结果
// export const LOGIN_OUT = url+'/logout';//登出
// export const LEADER_BOARD = url+'/leaderboard';//总排行榜
// export const USER_READY = url+'/user_ready';//总排行榜
// export const SIGN_LIST = url+'/sign_list';//签到
// export const USER_SIGN = url+'/user_sign';//签到
// export const MEDAL_INFO = url+'/medal_info';//勋章单个信息
// export const WATCH_GAME = url+'/watch_game';//勋章单个信息
// export const RECEIVE_GOLD = url+'/receive_gold';//勋章单个信息
// export const DAILY_TASK_LIST = url+'/daily_task_list';//勋章单个信息
// export const ACHIEVEMENT_LIST = url+'/achievement_list';//勋章单个信息
// export const RECEIVE_ACHIEVEMENT_TASK = url+'/receive_achievement_task';//勋章单个信息
// export const RECEIVE_DAILY_TASK = url+'/receive_daily_task';//勋章单个信息
// export const ONLINE_FRIEND = url+'/online_friend';//勋章单个信息
// export const INVITE_FRIEND = url+'/invite_friend';//勋章单个信息
// export const STRANGER = url+'/stranger';//勋章单个信息
// export const INVITE_FRIEND_JOIN = url+'/invite_friend_join';//勋章单个信息
// export const SET_MUSIC = url+'/set_music';//设置音乐
// export const SET_SOUND_EFFECT = url+'/set_sound_effect';//设置音乐
// export const SET_SHIELD = url+'/set_shield';//设置音乐
// export const SET_WATCH = url+'/set_watch';//设置音乐
// export const INDEX_WXLOGIN_LOGIN = url+'/index/wxlogin/login';//设置音乐
// export const ONLINE_USER = url+'/online_user';//设置音乐
// export const SHARE_GETSIGN = url+'/index/Share/getSignPackage';//设置音乐
// export const SET_INFO = url+'/set_info';//设置音乐
// export const USER_READY_HOME = url+'/user_ready_home';//设置音乐
// export const BIND_PHONE = url+'/bind_phone';//设置音乐
// export const KICK_PEOPLE = url+'/kick_people';//设置音乐
// export const RED_ENVELOPE = url+'/red_envelope';//踢人
// export const RECHARGE_ACTIVE = url+'/recharge_active';//踢人
// export const DEL_FRIEND = url+'/del_friend';//踢人
// export const FORGET_PASSWORD = url+'/forget_password';//踢人
// export const GET_TIME = url+'/get_time';//踢人
// export const SYS_SEND_MESSAGE = url+'/sys_send_message';//踢人
// export const FORGET_SEND_VERIFI_CODE = url+'/forget_send_verifi_code';//获取验证码
// export const IS_RECIVE_ACTIVE = url+'/index/task/is_recive_active';//踢人
// export const SIGN_USER_SIGN = url+'/index/signature/user_sign';//踢人
// export const EDIT_SIGN = url+'/index/signature/edit_sign';//踢人
// export const PUSH_ROOM_SPEAK = url+'/push/room/speak';//踢人
// export const RECEIVE_SILVER = url+'/receive_silver';//踢人
// export const IS_RECEIVE_SILVER = url+'/is_recive_silver';//踢人
// export const MEMBER_EXPIRE = url+'/member_expire';//会员信息
// export const REFUND_REQUEST = url+'/refund_request';//退款
// export const REFUNF_MONEY_NUM = url+'/refund_money_num';//退款
// export const BUY_VIP = url+'/buy_vip';//购买续费vip
// export const TREASURE_JOIN_GROUP = url+'/treasure/group/join_group';//加入宝箱房间
// export const TREASURE_GRAB_BAG = url+'/treasure/group/grab_bag';//加入宝箱房间
// export const USER_GOLD = url+'/index/user/user_gold';//加入宝箱房间
// export const PACKAGE_RECORD = url+'/treasure/group/package_record';//加入宝箱房间
// export const TODAY_GRABBED_RECORD = url+'/treasure/group/today_grabbed_record';//加入宝箱房间

// export const GET_LOGIN_CAPTCHA        = '/api/login/captcha';
// export const LOGIN                    = '/api/login';                                //登录
// export const REGISTER                 = '/api/register';                             //注册
// export const SEND_VERIFI_CODE         = '/api/send_verifi_code';                     //获取验证码
// export const BIND_SEND_VERIFI_CODE    = '/api/bind_send_verifi_code';                //获取验证码
// export const FORGET_SEND_VERIFI_CODE  = '/api/forget_send_verifi_code';              //获取验证码
// export const GET_LEADER_BOARD         = '/api/leaderboard';                          //查看排行榜
// export const GET_USER_MEDAL           = '/api/user_medal';                           //个人勋章列表
// export const GET_USER_INFO            = '/api/user_info';                            //个人勋章列表
// export const EDIT_USERNAME            = '/api/edit_username';                        //个人勋章列表
// export const COUPON                   = '/api/coupon';                               //活动页优惠券
// export const JOIN_ROOM_ID             = '/api/join_room_id';                         //加入房间
// export const CREATE_ROOM              = '/api/create_room';                          //创建房间
// export const CONFIRM_ROOM_PASS        = '/api/confirm_room_pass';                    //验证房间密码
// export const RADOME_JOIN_ROOM         = '/api/join_room';                            //加入房间
// export const UPLOAD_MY_HEAD           = '/api/upload';                               //上传头像
// export const UPDATE_USERINFO          = '/api/update_userinfo';                      //更新用户信息
// export const ADD_USER_LIST            = '/api/add_user_list';                        //添加好友列表
// export const BATCH_AGREE_APPLY        = '/api/batch_agree_apply';                    //同意添加好友
// export const OTHER_USER_INFO          = '/api/other_user_info';                      //好友信息
// export const BATCH_REFUSE_APPLY       = '/api/batch_refuse_apply';                   //拒绝添加好友
// export const BATCH_ADD_USER           = '/api/batch_add_user';                       //申请添加好友
// export const SELF_FRIEND              = '/api/self_friend';                          //好友列表
// export const BEGIN_GAME               = '/api/begin_game';                           //开始游戏
// export const CHALL_RES                = '/api/chall_res';                            //游戏结果
// export const LOGIN_OUT                = '/api/logout';                               //登出
// export const LEADER_BOARD             = '/api/leaderboard';                          //总排行榜
// export const USER_READY               = '/api/user_ready';                           //总排行榜
// export const SIGN_LIST                = '/api/sign_list';                            //签到
// export const USER_SIGN                = '/api/user_sign';                            //签到
// export const MEDAL_INFO               = '/api/medal_info';                           //勋章单个信息
// export const WATCH_GAME               = '/api/watch_game';                           //勋章单个信息
// export const RECEIVE_GOLD             = '/api/receive_gold';                         //勋章单个信息
// export const DAILY_TASK_LIST          = '/api/daily_task_list';                      //勋章单个信息
// export const ACHIEVEMENT_LIST         = '/api/achievement_list';                     //勋章单个信息
// export const RECEIVE_ACHIEVEMENT_TASK = '/api/receive_achievement_task';             //勋章单个信息
// export const RECEIVE_DAILY_TASK       = '/api/receive_daily_task';                   //勋章单个信息
// export const ONLINE_FRIEND            = '/api/online_friend';                        //勋章单个信息
// export const INVITE_FRIEND            = '/api/invite_friend';                        //勋章单个信息
// export const STRANGER                 = '/api/stranger';                             //勋章单个信息
// export const INVITE_FRIEND_JOIN       = '/api/invite_friend_join';                   //勋章单个信息
// export const SET_MUSIC                = '/api/set_music';                            //设置音乐
// export const SET_SOUND_EFFECT         = '/api/set_sound_effect';                     //设置音乐
// export const SET_SHIELD               = '/api/set_shield';                           //设置音乐
// export const SET_WATCH                = '/api/set_watch';                            //设置音乐
// export const INDEX_WXLOGIN_LOGIN      = '/api/index/wxlogin/login';                  //设置音乐
// export const ONLINE_USER              = '/api/online_user';                          //设置音乐
// export const SHARE_GETSIGN            = '/api/index/Share/getSignPackage';           //设置音乐
// export const SET_INFO                 = '/api/set_info';                             //个人设置信息
// export const USER_READY_HOME          = '/api/user_ready_home';                      //房主返回房间查看准备
// export const BIND_PHONE               = '/api/bind_phone';                           //绑定手机
// export const KICK_PEOPLE              = '/api/kick_people';                          //踢人
// export const RED_ENVELOPE             = '/api/red_envelope';                         //踢人
// export const RECHARGE_ACTIVE          = '/api/recharge_active';                      //踢人
// export const DEL_FRIEND               = '/api/del_friend';                           //踢人
// export const FORGET_PASSWORD          = '/api/forget_password';                      //踢人
// export const GET_TIME                 = '/api/get_time';                             //踢人
// export const SYS_SEND_MESSAGE         = '/api/sys_send_message';                     //踢人
// export const IS_RECIVE_ACTIVE         = '/api/index/task/is_recive_active';          //踢人
// export const SIGN_USER_SIGN           = '/api/index/signature/user_sign';            //踢人
// export const EDIT_SIGN                = '/api/index/signature/edit_sign';            //编辑二维码信息
// export const PUSH_ROOM_SPEAK          = '/api/push/room/speak';                      //说话
// export const RECEIVE_SILVER           = '/api/receive_silver';                       //领取银币
// export const IS_RECEIVE_SILVER        = '/api/is_recive_silver';                     //是否已经领取银币
// export const MEMBER_EXPIRE            = '/api/member_expire';                        //会员信息
// export const REFUND_REQUEST           = '/api/refund_request';                       //退款
// export const REFUNF_MONEY_NUM         = '/api/refund_money_num';                     //退款
// export const BUY_VIP                  = '/api/buy_vip';                              //购买续费vip
// export const TREASURE_JOIN_GROUP      = '/api/treasure/group/join_group';            //加入宝箱房间
// export const TREASURE_GRAB_BAG        = '/api/treasure/group/grab_bag';              //加入宝箱房间
// export const USER_GOLD                = '/api/index/user/user_gold';                 //加入宝箱房间
// export const PACKAGE_RECORD           = '/api/treasure/group/package_record';        //加入宝箱房间
// export const TODAY_GRABBED_RECORD     = '/api/treasure/group/today_grabbed_record';  //加入宝箱房间

